services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: IndustriasCTS
      MYSQL_ROOT_PASSWORD: IndustriasCTS
      TZ: America/Bogota # Configurar la zona horaria
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql # Persistir datos de MySQL
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mysql-phpmyadmin
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    environment:
      - PORT=${PORT}
      - TZ=America/Bogota # Configurar la zona horaria para la aplicación
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
    stdin_open: true        # Habilita la entrada interactiva
    tty: true
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      PMA_USER: admin # Usuario de MySQL
      PMA_PASSWORD: IndustriasCTS # Contraseña del usuario
      MYSQL_ROOT_PASSWORD: IndustriasCTS # Debe coincidir con la contraseña de root en MySQL
      UPLOAD_LIMIT: 64M # Límite de carga para archivos
      TZ: America/Bogota # Configurar la zona horaria
    networks:
      - mysql-phpmyadmin
networks:
  mysql-phpmyadmin:
volumes:
  db_data: # Definido para persistir datos de la base de datos